#!/usr/bin/env python3
"""Regenerate scripts/lib/cozette-coverage.json from the shipped Cozette font.

The font ships as a vector woff2 (public/fonts/CozetteVector.woff2); PixiJS v8
BitmapText lazily bakes a per-glyph atlas from it, so a glyph the woff2 lacks
renders as .notdef (a blank tofu box) — an invisible feature. The glyph-
coverage smoke (scripts/smoke-glyph-coverage.mts) asserts every literal glyph
the renderers emit is in this coverage set; this script produces that set.

Requires fonttools + brotli:  pip install fonttools brotli
Run from the repo root:        python3 scripts/gen-cozette-coverage.py
Regenerate whenever the font in public/fonts/ changes.
"""
import json
import sys
from pathlib import Path

try:
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fonttools not installed — run: pip install fonttools brotli")

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "public" / "fonts" / "CozetteVector.woff2"
OUT = ROOT / "scripts" / "lib" / "cozette-coverage.json"

cps = sorted(TTFont(str(FONT)).getBestCmap().keys())
if not cps:
    sys.exit(f"no codepoints found in {FONT}")

# Compress the codepoint set to inclusive ranges so the snapshot stays small.
ranges = []
start = prev = cps[0]
for c in cps[1:]:
    if c == prev + 1:
        prev = c
        continue
    ranges.append([start, prev])
    start = prev = c
ranges.append([start, prev])

OUT.write_text(
    json.dumps(
        {
            "note": (
                "Codepoint coverage of public/fonts/CozetteVector.woff2 as "
                "inclusive ranges. Generated by scripts/gen-cozette-coverage.py "
                "(fonttools). Regenerate when the font changes."
            ),
            "count": len(cps),
            "ranges": ranges,
        },
        separators=(",", ":"),
    )
)
print(f"wrote {OUT} — {len(cps)} codepoints in {len(ranges)} ranges")
